language: elixir
sudo: false

env:
  - ELIXIR_ASSERT_TIMEOUT=2000
  
matrix:
  include:
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0

script:
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - paul@knoxen.com
