language: elixir
sudo: false

env:
  - ELIXIR_ASSERT_TIMEOUT=2000

elixir:
  - '1.8'
otp_release:
  - '21.2'

script:
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

notifications:
  recipients:
    - paul@knoxen.com
